"""Adding new fields in the tables

Revision ID: 030777a73fad
Revises: 96f3e935c8a1
Create Date: 2022-04-09 14:56:05.476032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030777a73fad'
down_revision = '96f3e935c8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'categories', 'merchants', ['merchant_id'], ['id'])
    op.add_column('items', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('merchants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('merchants', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'merchants', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merchants', type_='unique')
    op.alter_column('merchants', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('merchants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('items', 'created_at')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
