"""Adding fields

Revision ID: 30539c112caa
Revises: c499009e2d30
Create Date: 2022-04-08 12:57:08.728201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30539c112caa'
down_revision = 'c499009e2d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('email', sa.String(), nullable=False))
    op.add_column('merchants', sa.Column('password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'merchants', ['email'])
    op.create_unique_constraint(None, 'merchants', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merchants', type_='unique')
    op.drop_constraint(None, 'merchants', type_='unique')
    op.drop_column('merchants', 'password')
    op.drop_column('merchants', 'email')
    # ### end Alembic commands ###
