"""Adding new tables

Revision ID: 44fc18b3d8cf
Revises: 30539c112caa
Create Date: 2022-04-09 14:26:51.432549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44fc18b3d8cf'
down_revision = '30539c112caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('merchants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('merchants', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'merchants', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merchants', type_='unique')
    op.alter_column('merchants', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('merchants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('items')
    op.drop_table('categories')
    # ### end Alembic commands ###
